import type { CaseWaveThemeName } from "./registry";

export type CaseWaveThemeCategory =
  | "base"
  | "visual"
  | "semantic"
  | "behavior"
  | "premium"
  | "edge"
  | "background";

export interface CaseWaveThemeMeta {
  name: CaseWaveThemeName;
  label: string;
  category: CaseWaveThemeCategory;
  description: string;
}

export const caseWaveThemeMeta: CaseWaveThemeMeta[] = [
  { name: "accessibility", label: "Accessibility", category: "premium", description: "Accessibility theme preset." },
  { name: "agency-blueprint", label: "Agency Blueprint", category: "premium", description: "Agency Blueprint theme preset." },
  { name: "agency-grey", label: "Agency Grey", category: "premium", description: "Agency Grey theme preset." },
  { name: "agency-vault", label: "Agency Vault", category: "premium", description: "Agency Vault theme preset." },
  { name: "amber-archive", label: "Amber Archive", category: "premium", description: "Amber Archive theme preset." },
  { name: "amber-ops", label: "Amber Ops", category: "premium", description: "Amber Ops theme preset." },
  { name: "analyst", label: "Analyst", category: "premium", description: "Analyst theme preset." },
  { name: "analyst-desk", label: "Analyst Desk", category: "premium", description: "Analyst Desk theme preset." },
  { name: "archive-blue", label: "Archive Blue", category: "premium", description: "Archive Blue theme preset." },
  { name: "archive-blueprint", label: "Archive Blueprint", category: "premium", description: "Archive Blueprint theme preset." },
  { name: "archive-bronze", label: "Archive Bronze", category: "premium", description: "Archive Bronze theme preset." },
  { name: "archive-dust", label: "Archive Dust", category: "premium", description: "Archive Dust theme preset." },
  { name: "archive-gold", label: "Archive Gold", category: "premium", description: "Archive Gold theme preset." },
  { name: "archive-marble", label: "Archive Marble", category: "premium", description: "Archive Marble theme preset." },
  { name: "archive-microfilm", label: "Archive Microfilm", category: "premium", description: "Archive Microfilm theme preset." },
  { name: "archive-pearl", label: "Archive Pearl", category: "premium", description: "Archive Pearl theme preset." },
  { name: "archive-quartz", label: "Archive Quartz", category: "premium", description: "Archive Quartz theme preset." },
  { name: "archive-rust", label: "Archive Rust", category: "premium", description: "Archive Rust theme preset." },
  { name: "archive-sepia", label: "Archive Sepia", category: "premium", description: "Archive Sepia theme preset." },
  { name: "archive-stone", label: "Archive Stone", category: "premium", description: "Archive Stone theme preset." },
  { name: "arctic-intel", label: "Arctic İntel", category: "premium", description: "Arctic İntel theme preset." },
  { name: "atlas-blue", label: "Atlas Blue", category: "premium", description: "Atlas Blue theme preset." },
  { name: "atlas-paper", label: "Atlas Paper", category: "premium", description: "Atlas Paper theme preset." },
  { name: "aurora-command", label: "Aurora Command", category: "premium", description: "Aurora Command theme preset." },
  { name: "aurora-wire", label: "Aurora Wire", category: "premium", description: "Aurora Wire theme preset." },
  { name: "black-chamber", label: "Black Chamber", category: "premium", description: "Black Chamber theme preset." },
  { name: "black-ops", label: "Black Ops", category: "premium", description: "Black Ops theme preset." },
  { name: "blacksite", label: "Blacksite", category: "premium", description: "Blacksite theme preset." },
  { name: "bloodline-board", label: "Bloodline Board", category: "premium", description: "Bloodline Board theme preset." },
  { name: "blue-channel", label: "Blue Channel", category: "premium", description: "Blue Channel theme preset." },
  { name: "blue-evidence", label: "Blue Evidence", category: "premium", description: "Blue Evidence theme preset." },
  { name: "blue-ops", label: "Blue Ops", category: "premium", description: "Blue Ops theme preset." },
  { name: "blueprint", label: "Blueprint", category: "premium", description: "Blueprint theme preset." },
  { name: "blueprint-ops", label: "Blueprint Ops", category: "premium", description: "Blueprint Ops theme preset." },
  { name: "blueprint-paper", label: "Blueprint Paper", category: "premium", description: "Blueprint Paper theme preset." },
  { name: "blueprint-steel", label: "Blueprint Steel", category: "premium", description: "Blueprint Steel theme preset." },
  { name: "blueprint-tactical", label: "Blueprint Tactical", category: "premium", description: "Blueprint Tactical theme preset." },
  { name: "blue-vector", label: "Blue Vector", category: "premium", description: "Blue Vector theme preset." },
  { name: "breach", label: "Breach", category: "premium", description: "Breach theme preset." },
  { name: "briefing-room", label: "Briefing Room", category: "premium", description: "Briefing Room theme preset." },
  { name: "bunker", label: "Bunker", category: "premium", description: "Bunker theme preset." },
  { name: "carbon-signal", label: "Carbon Signal", category: "premium", description: "Carbon Signal theme preset." },
  { name: "caseboard-classic", label: "Caseboard Classic", category: "premium", description: "Caseboard Classic theme preset." },
  { name: "caseboard-graphite", label: "Caseboard Graphite", category: "premium", description: "Caseboard Graphite theme preset." },
  { name: "caseboard-ivory", label: "Caseboard İvory", category: "premium", description: "Caseboard İvory theme preset." },
  { name: "case-file", label: "Case File", category: "premium", description: "Case File theme preset." },
  { name: "casefile-premium", label: "Casefile Premium", category: "premium", description: "Casefile Premium theme preset." },
  { name: "case-room", label: "Case Room", category: "premium", description: "Case Room theme preset." },
  { name: "cipher", label: "Cipher", category: "premium", description: "Cipher theme preset." },
  { name: "cipher-navy", label: "Cipher Navy", category: "premium", description: "Cipher Navy theme preset." },
  { name: "cipher-paper", label: "Cipher Paper", category: "premium", description: "Cipher Paper theme preset." },
  { name: "cipher-storm", label: "Cipher Storm", category: "premium", description: "Cipher Storm theme preset." },
  { name: "circuit-edges", label: "Circuit Edges", category: "premium", description: "Circuit Edges theme preset." },
  { name: "classified", label: "Classified", category: "premium", description: "Classified theme preset." },
  { name: "cold-case", label: "Cold Case", category: "premium", description: "Cold Case theme preset." },
  { name: "cold-evidence", label: "Cold Evidence", category: "premium", description: "Cold Evidence theme preset." },
  { name: "cold-storage", label: "Cold Storage", category: "premium", description: "Cold Storage theme preset." },
  { name: "cold-trail", label: "Cold Trail", category: "premium", description: "Cold Trail theme preset." },
  { name: "command-black", label: "Command Black", category: "premium", description: "Command Black theme preset." },
  { name: "command-center", label: "Command Center", category: "premium", description: "Command Center theme preset." },
  { name: "command-ivory", label: "Command İvory", category: "premium", description: "Command İvory theme preset." },
  { name: "command-silver", label: "Command Silver", category: "premium", description: "Command Silver theme preset." },
  { name: "compact", label: "Compact", category: "premium", description: "Compact theme preset." },
  { name: "conspiracy-board", label: "Conspiracy Board", category: "premium", description: "Conspiracy Board theme preset." },
  { name: "corkboard", label: "Corkboard", category: "premium", description: "Corkboard theme preset." },
  { name: "cork-detective", label: "Cork Detective", category: "premium", description: "Cork Detective theme preset." },
  { name: "cork-evidence", label: "Cork Evidence", category: "premium", description: "Cork Evidence theme preset." },
  { name: "courtroom", label: "Courtroom", category: "premium", description: "Courtroom theme preset." },
  { name: "covert-signal", label: "Covert Signal", category: "premium", description: "Covert Signal theme preset." },
  { name: "crime-board-paper", label: "Crime Board Paper", category: "premium", description: "Crime Board Paper theme preset." },
  { name: "crime-ledger", label: "Crime Ledger", category: "premium", description: "Crime Ledger theme preset." },
  { name: "crime-network", label: "Crime Network", category: "premium", description: "Crime Network theme preset." },
  { name: "crime-scene-tape", label: "Crime Scene Tape", category: "premium", description: "Crime Scene Tape theme preset." },
  { name: "criminal-ink", label: "Criminal İnk", category: "premium", description: "Criminal İnk theme preset." },
  { name: "crimson-board", label: "Crimson Board", category: "premium", description: "Crimson Board theme preset." },
  { name: "crimson-intel", label: "Crimson İntel", category: "premium", description: "Crimson İntel theme preset." },
  { name: "crisis-cell", label: "Crisis Cell", category: "premium", description: "Crisis Cell theme preset." },
  { name: "cyber-evidence", label: "Cyber Evidence", category: "premium", description: "Cyber Evidence theme preset." },
  { name: "cyber-neon", label: "Cyber Neon", category: "premium", description: "Cyber Neon theme preset." },
  { name: "cyber-pulse", label: "Cyber Pulse", category: "premium", description: "Cyber Pulse theme preset." },
  { name: "cyberpunk", label: "Cyberpunk", category: "premium", description: "Cyberpunk theme preset." },
  { name: "dark", label: "Dark", category: "premium", description: "Dark theme preset." },
  { name: "dark-grid-matrix", label: "Dark Grid Matrix", category: "premium", description: "Dark Grid Matrix theme preset." },
  { name: "dark-matter", label: "Dark Matter", category: "premium", description: "Dark Matter theme preset." },
  { name: "darkroom", label: "Darkroom", category: "premium", description: "Darkroom theme preset." },
  { name: "dark-signal", label: "Dark Signal", category: "premium", description: "Dark Signal theme preset." },
  { name: "deep-archive", label: "Deep Archive", category: "premium", description: "Deep Archive theme preset." },
  { name: "deep-navy", label: "Deep Navy", category: "premium", description: "Deep Navy theme preset." },
  { name: "deep-signal", label: "Deep Signal", category: "premium", description: "Deep Signal theme preset." },
  { name: "deep-vault", label: "Deep Vault", category: "premium", description: "Deep Vault theme preset." },
  { name: "delta-ops", label: "Delta Ops", category: "premium", description: "Delta Ops theme preset." },
  { name: "dependency-graph", label: "Dependency Graph", category: "premium", description: "Dependency Graph theme preset." },
  { name: "detective-noir-2", label: "Detective Noir 2", category: "premium", description: "Detective Noir 2 theme preset." },
  { name: "digital-forensics", label: "Digital Forensics", category: "premium", description: "Digital Forensics theme preset." },
  { name: "dossier-black", label: "Dossier Black", category: "premium", description: "Dossier Black theme preset." },
  { name: "dossier-crimson", label: "Dossier Crimson", category: "premium", description: "Dossier Crimson theme preset." },
  { name: "embassy", label: "Embassy", category: "premium", description: "Embassy theme preset." },
  { name: "emerald-directive", label: "Emerald Directive", category: "premium", description: "Emerald Directive theme preset." },
  { name: "encrypted", label: "Encrypted", category: "premium", description: "Encrypted theme preset." },
  { name: "evidence-board", label: "Evidence Board", category: "premium", description: "Evidence Board theme preset." },
  { name: "evidence-copper", label: "Evidence Copper", category: "premium", description: "Evidence Copper theme preset." },
  { name: "evidence-folder-texture", label: "Evidence Folder Texture", category: "premium", description: "Evidence Folder Texture theme preset." },
  { name: "evidence-graphite", label: "Evidence Graphite", category: "premium", description: "Evidence Graphite theme preset." },
  { name: "evidence-locker", label: "Evidence Locker", category: "premium", description: "Evidence Locker theme preset." },
  { name: "evidence-redline", label: "Evidence Redline", category: "premium", description: "Evidence Redline theme preset." },
  { name: "evidence-room", label: "Evidence Room", category: "premium", description: "Evidence Room theme preset." },
  { name: "evidence-ruby", label: "Evidence Ruby", category: "premium", description: "Evidence Ruby theme preset." },
  { name: "evidence-tag", label: "Evidence Tag", category: "premium", description: "Evidence Tag theme preset." },
  { name: "evidence-thread", label: "Evidence Thread", category: "premium", description: "Evidence Thread theme preset." },
  { name: "evidence-vault", label: "Evidence Vault", category: "premium", description: "Evidence Vault theme preset." },
  { name: "evidence-wall-dark", label: "Evidence Wall Dark", category: "premium", description: "Evidence Wall Dark theme preset." },
  { name: "executive-slate", label: "Executive Slate", category: "premium", description: "Executive Slate theme preset." },
  { name: "federal-dossier", label: "Federal Dossier", category: "premium", description: "Federal Dossier theme preset." },
  { name: "field-ops", label: "Field Ops", category: "premium", description: "Field Ops theme preset." },
  { name: "focus", label: "Focus", category: "premium", description: "Focus theme preset." },
  { name: "forensic-frost", label: "Forensic Frost", category: "premium", description: "Forensic Frost theme preset." },
  { name: "forensic-lab", label: "Forensic Lab", category: "premium", description: "Forensic Lab theme preset." },
  { name: "forensic-mint", label: "Forensic Mint", category: "premium", description: "Forensic Mint theme preset." },
  { name: "forensic-paper", label: "Forensic Paper", category: "premium", description: "Forensic Paper theme preset." },
  { name: "forensics", label: "Forensics", category: "premium", description: "Forensics theme preset." },
  { name: "forensic-ultraviolet", label: "Forensic Ultraviolet", category: "premium", description: "Forensic Ultraviolet theme preset." },
  { name: "ghost-archive", label: "Ghost Archive", category: "premium", description: "Ghost Archive theme preset." },
  { name: "ghost-protocol", label: "Ghost Protocol", category: "premium", description: "Ghost Protocol theme preset." },
  { name: "ghost-wire", label: "Ghost Wire", category: "premium", description: "Ghost Wire theme preset." },
  { name: "glass", label: "Glass", category: "premium", description: "Glass theme preset." },
  { name: "gold-evidence", label: "Gold Evidence", category: "premium", description: "Gold Evidence theme preset." },
  { name: "graph-paper", label: "Graph Paper", category: "premium", description: "Graph Paper theme preset." },
  { name: "green-radar", label: "Green Radar", category: "premium", description: "Green Radar theme preset." },
  { name: "grid-command", label: "Grid Command", category: "premium", description: "Grid Command theme preset." },
  { name: "hand-drawn-edges", label: "Hand Drawn Edges", category: "premium", description: "Hand Drawn Edges theme preset." },
  { name: "hazard-orange", label: "Hazard Orange", category: "premium", description: "Hazard Orange theme preset." },
  { name: "hunter-green", label: "Hunter Green", category: "premium", description: "Hunter Green theme preset." },
  { name: "hunter-ops", label: "Hunter Ops", category: "premium", description: "Hunter Ops theme preset." },
  { name: "imperial-purple", label: "İmperial Purple", category: "premium", description: "İmperial Purple theme preset." },
  { name: "incident-amber", label: "İncident Amber", category: "premium", description: "İncident Amber theme preset." },
  { name: "incident-board", label: "İncident Board", category: "premium", description: "İncident Board theme preset." },
  { name: "incident-response", label: "İncident Response", category: "premium", description: "İncident Response theme preset." },
  { name: "infrared-threat", label: "İnfrared Threat", category: "premium", description: "İnfrared Threat theme preset." },
  { name: "intel-blue", label: "İntel Blue", category: "premium", description: "İntel Blue theme preset." },
  { name: "intel-ice", label: "İntel İce", category: "premium", description: "İntel İce theme preset." },
  { name: "intelligence-desk", label: "İntelligence Desk", category: "premium", description: "İntelligence Desk theme preset." },
  { name: "intelligence-map", label: "İntelligence Map", category: "premium", description: "İntelligence Map theme preset." },
  { name: "intel-mint", label: "İntel Mint", category: "premium", description: "İntel Mint theme preset." },
  { name: "intel-obsidian", label: "İntel Obsidian", category: "premium", description: "İntel Obsidian theme preset." },
  { name: "intel-paper", label: "İntel Paper", category: "premium", description: "İntel Paper theme preset." },
  { name: "intel-purple", label: "İntel Purple", category: "premium", description: "İntel Purple theme preset." },
  { name: "intel-rose", label: "İntel Rose", category: "premium", description: "İntel Rose theme preset." },
  { name: "intel-terminal", label: "İntel Terminal", category: "premium", description: "İntel Terminal theme preset." },
  { name: "intercept-grid", label: "İntercept Grid", category: "premium", description: "İntercept Grid theme preset." },
  { name: "interpol", label: "İnterpol", category: "premium", description: "İnterpol theme preset." },
  { name: "investigation", label: "İnvestigation", category: "premium", description: "İnvestigation theme preset." },
  { name: "iron-directive", label: "İron Directive", category: "premium", description: "İron Directive theme preset." },
  { name: "ivory-investigation", label: "İvory İnvestigation", category: "premium", description: "İvory İnvestigation theme preset." },
  { name: "large-graph", label: "Large Graph", category: "premium", description: "Large Graph theme preset." },
  { name: "light", label: "Light", category: "premium", description: "Light theme preset." },
  { name: "map-overlay", label: "Map Overlay", category: "premium", description: "Map Overlay theme preset." },
  { name: "matrix", label: "Matrix", category: "premium", description: "Matrix theme preset." },
  { name: "matrix-ops", label: "Matrix Ops", category: "premium", description: "Matrix Ops theme preset." },
  { name: "mercury-ops", label: "Mercury Ops", category: "premium", description: "Mercury Ops theme preset." },
  { name: "midnight", label: "Midnight", category: "premium", description: "Midnight theme preset." },
  { name: "midnight-grid", label: "Midnight Grid", category: "premium", description: "Midnight Grid theme preset." },
  { name: "mind-map", label: "Mind Map", category: "premium", description: "Mind Map theme preset." },
  { name: "minimal", label: "Minimal", category: "premium", description: "Minimal theme preset." },
  { name: "mint-cipher", label: "Mint Cipher", category: "premium", description: "Mint Cipher theme preset." },
  { name: "murder-wall", label: "Murder Wall", category: "premium", description: "Murder Wall theme preset." },
  { name: "neo-brutalist", label: "Neo Brutalist", category: "premium", description: "Neo Brutalist theme preset." },
  { name: "neon-crime", label: "Neon Crime", category: "premium", description: "Neon Crime theme preset." },
  { name: "neon-edges", label: "Neon Edges", category: "premium", description: "Neon Edges theme preset." },
  { name: "neon-intercept", label: "Neon İntercept", category: "premium", description: "Neon İntercept theme preset." },
  { name: "neural-crime", label: "Neural Crime", category: "premium", description: "Neural Crime theme preset." },
  { name: "night-amber", label: "Night Amber", category: "premium", description: "Night Amber theme preset." },
  { name: "night-cipher", label: "Night Cipher", category: "premium", description: "Night Cipher theme preset." },
  { name: "night-ops-red", label: "Night Ops Red", category: "premium", description: "Night Ops Red theme preset." },
  { name: "night-shift", label: "Night Shift", category: "premium", description: "Night Shift theme preset." },
  { name: "night-vector", label: "Night Vector", category: "premium", description: "Night Vector theme preset." },
  { name: "night-vision", label: "Night Vision", category: "premium", description: "Night Vision theme preset." },
  { name: "noir", label: "Noir", category: "premium", description: "Noir theme preset." },
  { name: "obsidian-grid", label: "Obsidian Grid", category: "premium", description: "Obsidian Grid theme preset." },
  { name: "omega-command", label: "Omega Command", category: "premium", description: "Omega Command theme preset." },
  { name: "onyx-vault", label: "Onyx Vault", category: "premium", description: "Onyx Vault theme preset." },
  { name: "operations-room", label: "Operations Room", category: "premium", description: "Operations Room theme preset." },
  { name: "ops-amber", label: "Ops Amber", category: "premium", description: "Ops Amber theme preset." },
  { name: "ops-blueprint-dark", label: "Ops Blueprint Dark", category: "premium", description: "Ops Blueprint Dark theme preset." },
  { name: "ops-mercury", label: "Ops Mercury", category: "premium", description: "Ops Mercury theme preset." },
  { name: "ops-polar", label: "Ops Polar", category: "premium", description: "Ops Polar theme preset." },
  { name: "ops-slate", label: "Ops Slate", category: "premium", description: "Ops Slate theme preset." },
  { name: "ops-steel", label: "Ops Steel", category: "premium", description: "Ops Steel theme preset." },
  { name: "ops-volt", label: "Ops Volt", category: "premium", description: "Ops Volt theme preset." },
  { name: "osint", label: "Osint", category: "premium", description: "Osint theme preset." },
  { name: "paper-archive", label: "Paper Archive", category: "premium", description: "Paper Archive theme preset." },
  { name: "paper-dossier", label: "Paper Dossier", category: "premium", description: "Paper Dossier theme preset." },
  { name: "paper-stamp", label: "Paper Stamp", category: "premium", description: "Paper Stamp theme preset." },
  { name: "phantom-ops", label: "Phantom Ops", category: "premium", description: "Phantom Ops theme preset." },
  { name: "phantom-purple", label: "Phantom Purple", category: "premium", description: "Phantom Purple theme preset." },
  { name: "pinboard", label: "Pinboard", category: "premium", description: "Pinboard theme preset." },
  { name: "platinum-command", label: "Platinum Command", category: "premium", description: "Platinum Command theme preset." },
  { name: "polar-signal", label: "Polar Signal", category: "premium", description: "Polar Signal theme preset." },
  { name: "police-desk", label: "Police Desk", category: "premium", description: "Police Desk theme preset." },
  { name: "police-dossier-paper", label: "Police Dossier Paper", category: "premium", description: "Police Dossier Paper theme preset." },
  { name: "presentation", label: "Presentation", category: "premium", description: "Presentation theme preset." },
  { name: "protocol-white", label: "Protocol White", category: "premium", description: "Protocol White theme preset." },
  { name: "quantum-intel", label: "Quantum İntel", category: "premium", description: "Quantum İntel theme preset." },
  { name: "quantum-pulse", label: "Quantum Pulse", category: "premium", description: "Quantum Pulse theme preset." },
  { name: "radar", label: "Radar", category: "premium", description: "Radar theme preset." },
  { name: "radar-violet", label: "Radar Violet", category: "premium", description: "Radar Violet theme preset." },
  { name: "recon", label: "Recon", category: "premium", description: "Recon theme preset." },
  { name: "redacted-file", label: "Redacted File", category: "premium", description: "Redacted File theme preset." },
  { name: "red-cell", label: "Red Cell", category: "premium", description: "Red Cell theme preset." },
  { name: "red-ledger", label: "Red Ledger", category: "premium", description: "Red Ledger theme preset." },
  { name: "red-string-board", label: "Red String Board", category: "premium", description: "Red String Board theme preset." },
  { name: "red-string-elite", label: "Red String Elite", category: "premium", description: "Red String Elite theme preset." },
  { name: "red-wire", label: "Red Wire", category: "premium", description: "Red Wire theme preset." },
  { name: "retro-terminal", label: "Retro Terminal", category: "premium", description: "Retro Terminal theme preset." },
  { name: "retro-terminal-amber", label: "Retro Terminal Amber", category: "premium", description: "Retro Terminal Amber theme preset." },
  { name: "rust-intel", label: "Rust İntel", category: "premium", description: "Rust İntel theme preset." },
  { name: "safehouse", label: "Safehouse", category: "premium", description: "Safehouse theme preset." },
  { name: "satellite-ops", label: "Satellite Ops", category: "premium", description: "Satellite Ops theme preset." },
  { name: "secret-archive", label: "Secret Archive", category: "premium", description: "Secret Archive theme preset." },
  { name: "secure-channel", label: "Secure Channel", category: "premium", description: "Secure Channel theme preset." },
  { name: "shadow-dossier", label: "Shadow Dossier", category: "premium", description: "Shadow Dossier theme preset." },
  { name: "shadow-intel", label: "Shadow İntel", category: "premium", description: "Shadow İntel theme preset." },
  { name: "signal-aurora", label: "Signal Aurora", category: "premium", description: "Signal Aurora theme preset." },
  { name: "signal-black", label: "Signal Black", category: "premium", description: "Signal Black theme preset." },
  { name: "signal-copper", label: "Signal Copper", category: "premium", description: "Signal Copper theme preset." },
  { name: "signal-crimson", label: "Signal Crimson", category: "premium", description: "Signal Crimson theme preset." },
  { name: "signal-intercept", label: "Signal İntercept", category: "premium", description: "Signal İntercept theme preset." },
  { name: "signal-mint", label: "Signal Mint", category: "premium", description: "Signal Mint theme preset." },
  { name: "signal-prism", label: "Signal Prism", category: "premium", description: "Signal Prism theme preset." },
  { name: "signal-room", label: "Signal Room", category: "premium", description: "Signal Room theme preset." },
  { name: "signal-teal", label: "Signal Teal", category: "premium", description: "Signal Teal theme preset." },
  { name: "silent-protocol", label: "Silent Protocol", category: "premium", description: "Silent Protocol theme preset." },
  { name: "sketch-edges", label: "Sketch Edges", category: "premium", description: "Sketch Edges theme preset." },
  { name: "soc-analyst", label: "Soc Analyst", category: "premium", description: "Soc Analyst theme preset." },
  { name: "specter-ops", label: "Specter Ops", category: "premium", description: "Specter Ops theme preset." },
  { name: "stealth-blue", label: "Stealth Blue", category: "premium", description: "Stealth Blue theme preset." },
  { name: "stealth-forest", label: "Stealth Forest", category: "premium", description: "Stealth Forest theme preset." },
  { name: "strike-team", label: "Strike Team", category: "premium", description: "Strike Team theme preset." },
  { name: "surveillance", label: "Surveillance", category: "premium", description: "Surveillance theme preset." },
  { name: "surveillance-green", label: "Surveillance Green", category: "premium", description: "Surveillance Green theme preset." },
  { name: "tactical-blackout", label: "Tactical Blackout", category: "premium", description: "Tactical Blackout theme preset." },
  { name: "tactical-emerald", label: "Tactical Emerald", category: "premium", description: "Tactical Emerald theme preset." },
  { name: "tactical-forest", label: "Tactical Forest", category: "premium", description: "Tactical Forest theme preset." },
  { name: "tactical-graphite", label: "Tactical Graphite", category: "premium", description: "Tactical Graphite theme preset." },
  { name: "tactical-grid", label: "Tactical Grid", category: "premium", description: "Tactical Grid theme preset." },
  { name: "tactical-ops", label: "Tactical Ops", category: "premium", description: "Tactical Ops theme preset." },
  { name: "tactical-rust", label: "Tactical Rust", category: "premium", description: "Tactical Rust theme preset." },
  { name: "tactical-sand", label: "Tactical Sand", category: "premium", description: "Tactical Sand theme preset." },
  { name: "terminal", label: "Terminal", category: "premium", description: "Terminal theme preset." },
  { name: "terminal-lime", label: "Terminal Lime", category: "premium", description: "Terminal Lime theme preset." },
  { name: "threat-grid-x", label: "Threat Grid X", category: "premium", description: "Threat Grid X theme preset." },
  { name: "threat-intel", label: "Threat İntel", category: "premium", description: "Threat İntel theme preset." },
  { name: "threat-matrix", label: "Threat Matrix", category: "premium", description: "Threat Matrix theme preset." },
  { name: "threat-radar", label: "Threat Radar", category: "premium", description: "Threat Radar theme preset." },
  { name: "topographic-map", label: "Topographic Map", category: "premium", description: "Topographic Map theme preset." },
  { name: "urban-ops", label: "Urban Ops", category: "premium", description: "Urban Ops theme preset." },
  { name: "vault-black", label: "Vault Black", category: "premium", description: "Vault Black theme preset." },
  { name: "vault-copper", label: "Vault Copper", category: "premium", description: "Vault Copper theme preset." },
  { name: "vault-ivory", label: "Vault İvory", category: "premium", description: "Vault İvory theme preset." },
  { name: "vault-noir", label: "Vault Noir", category: "premium", description: "Vault Noir theme preset." },
  { name: "vector-mint", label: "Vector Mint", category: "premium", description: "Vector Mint theme preset." },
  { name: "volt-matrix", label: "Volt Matrix", category: "premium", description: "Volt Matrix theme preset." },
  { name: "warboard", label: "Warboard", category: "premium", description: "Warboard theme preset." },
  { name: "war-room", label: "War Room", category: "premium", description: "War Room theme preset." },
  { name: "warroom-classic", label: "Warroom Classic", category: "premium", description: "Warroom Classic theme preset." },
  { name: "watchfloor", label: "Watchfloor", category: "premium", description: "Watchfloor theme preset." },
  { name: "windows-95", label: "Windows 95", category: "premium", description: "Windows 95 theme preset." },
  { name: "wireframe-edges", label: "Wireframe Edges", category: "premium", description: "Wireframe Edges theme preset." },
  { name: "wireframe-ops", label: "Wireframe Ops", category: "premium", description: "Wireframe Ops theme preset." },
  { name: "wiregrid", label: "Wiregrid", category: "premium", description: "Wiregrid theme preset." },
  { name: "wiretap", label: "Wiretap", category: "premium", description: "Wiretap theme preset." },
];

export function getCaseWaveThemesByCategory(category: CaseWaveThemeCategory) {
  return caseWaveThemeMeta.filter((theme) => theme.category === category);
}

export function getCaseWaveThemeMeta(name: CaseWaveThemeName) {
  return caseWaveThemeMeta.find((theme) => theme.name === name);
}
